# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 928cb5c6395c7ae03192f8ef8abdf707b0a074a222adedfcd9c2335e266d5a933d52ca6e43b45898c2ebd767242a2b543d90e391e692ad7c81ca459d7182f6d4

test:
  secret_key_base: 61e6561313ad8178b30f9c929cb1f8fd5bbcd09857790698928dc0521c436d280409ac4de7167145f2e727e4b372ae3cce646f02ec60af07a17c54cba910941b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
